[TPD-14] Jump improvments
abby1332/TigerDev-PS pull request #11
Opened 2024-09-16 20:44 UTC by CarterHague

Added in jump-input buffering and jump cuts to the player controller

2024-09-16 21:20 UTC, abby1332 approved these changes

2024-09-16 23:09 UTC, funkychicken493 requested changes

2024-09-16 23:09 UTC, funkychicken493 commented on player.gd
> +				velocity += get_gravity() * delta
too much indent

2024-09-19 17:18 UTC, funkychicken493 approved these changes

2024-09-19 17:18 UTC, merged