Add Posterization Shader with Dithering
abby1332/TigerDev-PS pull request #20
Opened 2024-10-01 01:48 UTC by ASlightlyOvergrownCactus

Don't worry about the crazy amount of changed files, most of them are just the palette images.

Adds a shader within a test scene that posterizes the entire screen to be a set of colors from a given palette, with dithering from a given bayer matrix. This is meant to be an option for a route of art style that we could take if we want to ^.^, but no worries if not.

2024-10-02 15:03 UTC, funkychicken493 requested changes

2024-10-02 15:03 UTC, funkychicken493 commented on resources/Shaders/TestImages/mainmenu.png
mainmenu.png needs to be removed we do not have rights to this image

2024-10-02 15:14 UTC, ASlightlyOvergrownCactus commented on resources/Shaders/TestImages/mainmenu.png
ughhhh booooooring

2024-10-02 16:28 UTC, funkychicken493 requested changes
Delete the .godot folder and merge from main

2024-10-27 18:43 UTC, ASlightlyOvergrownCactus commented
Ok, .godot folder is fixed and ready to merge

2024-10-27 18:44 UTC, funkychicken493 approved these changes
LGTM

2024-11-01 20:00 UTC, AhmadAJabr approved these changes
Approved

2024-11-01 22:12 UTC, merged